site_name: Yiheng的笔记本
site_url: http://codeheng.github.io
repo_name: Yiheng's NoteBook
repo_url: https://github.com/codeheng/codeheng.github.io

nav:
  - 🏡 主页: 
    - index.md
    - ❤️ 关于我: home/about.md  

  - 📖知识:
    - core_knowledge/index.md
    - 算法:
      - LeetCode刷题打卡:
        - 数组: 
          - Day1 | Part1: core_knowledge/algorithm/check_in_everyday/day1.md
          - Day2 | Part2: core_knowledge/algorithm/check_in_everyday/day2.md
        - 链表:
          - Day3 | Part1: core_knowledge/algorithm/check_in_everyday/day3.md
          - Day4 | Part2: core_knowledge/algorithm/check_in_everyday/day4.md
        - 哈希表:
          - Day5 | Part1: core_knowledge/algorithm/check_in_everyday/day5.md
          - Day6 | Part2: core_knowledge/algorithm/check_in_everyday/day6.md
        - 字符串: 
          - Day7 | Part1: core_knowledge/algorithm/check_in_everyday/day7.md
        - 栈和队列: 
          - Day8 | Part1: core_knowledge/algorithm/check_in_everyday/day8.md
          - Day9 | Part2: core_knowledge/algorithm/check_in_everyday/day9.md
          - Day10 | Part3: core_knowledge/algorithm/check_in_everyday/day10.md
        - 二叉树: 
          - Day11 | Part1: core_knowledge/algorithm/check_in_everyday/day11.md
          - Day12 | Part2: core_knowledge/algorithm/check_in_everyday/day12.md
          - Day13 | Part3: core_knowledge/algorithm/check_in_everyday/day13.md
          - Day14 | Part4: core_knowledge/algorithm/check_in_everyday/day14.md
          - Day15 | Part5: core_knowledge/algorithm/check_in_everyday/day15.md
          - Day16 | Part6: core_knowledge/algorithm/check_in_everyday/day16.md
          - Day17 | Part7: core_knowledge/algorithm/check_in_everyday/day17.md
          - Day18 | Part8: core_knowledge/algorithm/check_in_everyday/day18.md
          - Day19 | Part9: core_knowledge/algorithm/check_in_everyday/day19.md
        - 回溯算法:
          - Day20 | Part1: core_knowledge/algorithm/check_in_everyday/day20.md
          - Day21 | Part2: core_knowledge/algorithm/check_in_everyday/day21.md
          - Day22 | Part3: core_knowledge/algorithm/check_in_everyday/day22.md
          - Day23 | Part4: core_knowledge/algorithm/check_in_everyday/day23.md
          - Day24 | Part5: core_knowledge/algorithm/check_in_everyday/day24.md
          - Day25 | Part6: core_knowledge/algorithm/check_in_everyday/day25.md
        - 贪心算法: 
          - Day26 | Part1: core_knowledge/algorithm/check_in_everyday/day26.md
          - Day27 | Part2: core_knowledge/algorithm/check_in_everyday/day27.md
          - Day28 | Part3: core_knowledge/algorithm/check_in_everyday/day28.md
          - Day29 | Part4: core_knowledge/algorithm/check_in_everyday/day29.md
          - Day30 | Part5: core_knowledge/algorithm/check_in_everyday/day30.md
          - Day31 | Part6: core_knowledge/algorithm/check_in_everyday/day31.md
        - 动态规划:
          - Day32 | Part1: core_knowledge/algorithm/check_in_everyday/day32.md
          - Day33 | Part2: core_knowledge/algorithm/check_in_everyday/day33.md
          - Day34 | Part3: core_knowledge/algorithm/check_in_everyday/day34.md
          - Day35 | Part4: core_knowledge/algorithm/check_in_everyday/day35.md
          - Day36 | Part5: core_knowledge/algorithm/check_in_everyday/day36.md
    - Linux: 
      - 基础: core_knowledge/linux/1-basic.md
    - C++:
      - core_knowledge/language/c++/index.md
      - CS106L:
        - 基础: core_knowledge/language/c++/cs106l/1-intro.md
        - 容器: core_knowledge/language/c++/cs106l/2-container.md
    - Java:
      - Docker: core_knowledge/language/java/docker.md
      - MySQL: core_knowledge/language/java/mysql.md
      - Redis: core_knowledge/language/java/redis.md
      - Maven: core_knowledge/language/java/maven.md 
      - SpringBoot: core_knowledge/language/java/springboot.md
    - Lab:
      - CSAPP:
        - core_knowledge/lab/csapp/index.md
        - DataLab: core_knowledge/lab/csapp/01datalab.md
    - Exam:
      - 金监管: core_knowledge/exam/RFRA-CS.md
      - 金融经济: core_knowledge/exam/financial_economics.md
  
  - 🔐安全:
    - security_etc/index.md
    - CS161:
      - 介绍: security_etc/intro.md
      - 密码学:
        - 概述: security_etc/cryptography/1-intro.md
        - 对称加密: 
          - 对称加密介绍: security_etc/cryptography/2-symmetric-key.md
          - 一次性密码本: security_etc/cryptography/3-one_time_pad.md
          - 分组密码: security_etc/cryptography/4-Block-Ciphers.md
          - 分组密码的操作模式: security_etc/cryptography/5-BC_Opera.md
          - MACs: security_etc/cryptography/7-MACs.md
          - 流密码: security_etc/cryptography/9-stream.md
        - 密码散列: security_etc/cryptography/6-hash.md
        - 伪随机数生成器: security_etc/cryptography/8-PRNGs.md
        - Diffie-Hellman: security_etc/cryptography/10-Diffie_Hellman.md
        - 公钥密码: security_etc/cryptography/11-Public-key_Cryptography.md
        - 数字签名: security_etc/cryptography/12-digital_signatures.md
        - 证书: security_etc/cryptography/13-certificates.md
        - 密码哈希: security_etc/cryptography/14-pwd_hashing.md
        - 比特币: security_etc/cryptography/bitcoin.md
    - 安全攻防:
      - 介绍: security_etc/attack_defense/intro_attack_defense.md
      - web安全: security_etc/attack_defense/web_security.md
      - 防御工具: security_ect/attack_defense/defense_tools.md

    - 区块链: 
      - 概述: security_etc/blockchain/1-blockchain.md
      - 区块链简介: security_etc/blockchain/2-intro.md
      - 区块链:加密和挖矿: security_etc/blockchain/3-chapter.md
      - 去中心化共识机制: security_etc/blockchain/4-chapter.md
      - 智能合约: security_etc/blockchain/5-smart_contract.md

    - 《区块链技术与应用》:
      - 01简介: security_etc/course/blockchain/01_intro.md
      - 比特币BTC: 
        - 02密码学原理: security_etc/course/blockchain/bitcoin/02_cryto.md
        - 03数据结构: security_etc/course/blockchain/bitcoin/03_data_structure.md
        - 04协议: security_etc/course/blockchain/bitcoin/04_protocol.md
        - 05实现: security_etc/course/blockchain/bitcoin/05_BTC实现.md
        - 06网络: security_etc/course/blockchain/bitcoin/06_BTC_internet.md
        - 07挖矿难度: security_etc/course/blockchain/bitcoin/07_BTC_挖矿难度.md
        - 08分叉: security_etc/course/blockchain/bitcoin/08_BTC_fork.md
        - 09匿名性: security_etc/course/blockchain/bitcoin/09_BTC_anonymity.md

    - 电动汽车与能源互联网:
      - 概述: security_etc/EvAndEI/intro.md
      - 需求响应: security_etc/EvAndEI/dr.md
      - 虚拟电厂: security_etc/EvAndEI/vpp.md

    - 科研:
      - security_etc/paper/index.md
      - 师门论文: security_etc/paper/master_homegate_paper.md
      - 论文记录: security_etc/paper/paper_records.md
      - 理论知识:
        - ECDLP: security_etc/paper/knowledge/ecdlp.md
        - V2G: security_etc/paper/knowledge/v2g.md
        - 无证书公钥密码: security_etc/paper/knowledge/cl_pkc.md
        - 双线性映射: security_etc/paper/knowledge/bilinear_pairing.md
        - 量子加密: security_etc/paper/knowledge/quantum_crypto.md
        - 可证明安全: security_etc/paper/knowledge/provably_secure.md
      - 实验:
        - 库: security_etc/paper/tool/lib.md
        - 密码学符号: security_etc/paper/tool/symbol.md
  
  
  - 🔍杂项:
    - mess/index.md
    - 工具收集: mess/tool.md
    - MarkDown: mess/markdown.md
    - LaTex: mess/latex.md
    - Vim: mess/Vim.md
    - VScode: mess/vscode.md


  - 🔑Eng:
    - eng/index.md
    - 单词: eng/word.md
    - 作文积累: eng/writing.md


  - 📚书籍: 
    - writing_note/index.md
    - 24读书记录: writing_note/24_book_records.md
    - 25读书记录: writing_note/25_book_records.md

  - 💡生活:
    - life/index.md
    - 2023年度总结: life/2024/2023final.md
    - 2024:
      - 1月: life/2024/24_january.md
      - 2月: life/2024/24_february.md
      - 3月: life/2024/24_march.md
      - 4月: life/2024/24_april.md
      - 5月: life/2024/24_may.md
      - 6月: life/2024/24_june.md
      - 下半年: life/2024/24_last_half_years.md
    - 2024年度总结: life/2024/24final.md
    - 2025:
      - 上半年: life/2025/25_first.md
      - 下半年: life/2025/25_last.md
    - 2025年度总结: life/2025/2025final.md
    - 2026:
      - 上半年: life/2026/2026_first.md
      - 毕业记录: life/2026/2026_graduation.md
  
  - 💪Workout:
    - workout/index.md
    - Zone 2: workout/zone2.md
    - 血压和血糖: workout/bp_bs.md
    - 饮食: workout/food.md
    - 健身记录: workout/records.md
    - 健身动作: workout/fitness_moves.md
    - 新手解剖课: workout/joint.md

  - 📂Attachment: 
    - attachment/index.md
    - Slide: attachment/ppt/slide.md

theme: 
  name: material
  favicon: assets/logo.ico

  icon: 
    logo: material/school-outline
  
  features:
    - search.highlight
    - navigation.tabs # 一级导航在横着的导航栏
    - navigation.instant # 即时加载 ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#:~:text=%C2%B6-,Instant%20loading,%C2%B6,-5.0.0
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    #- navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    # - navigation.sections # 二级导航是粗体
    # - navigation.expand # 导航默认展开
    - toc.follow # toc 跟随
    # - toc.integrate # 文档 toc 集成到总目录中
    - content.code.copy
    - content.footnote.tooltips
  
  font: 
    text: Noto Serif SC
    code: Roboto Mono
  
  language: 'zh'

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        
  custom_dir: overrides # 用来搞评论的，参考 https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

extra:
  analytics:
    provider: google
    #property: G-JT9BRCXKJJ
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codeheng
    - icon: fontawesome/solid/envelope
      link: mailto:yihenghhh@gmail.com


edit_uri: ""
copyright: '本页面的全部内容在 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a> 协议之条款下提供，附加条款亦可能应用'

extra_css:
  - stylesheets/extra.css
  - stylesheets/status.css
  - stylesheets/card.css

extra_javascript:
  - javascripts/mathjax.js # 支持数学公式，ref : https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/twemoji@latest/dist/twemoji.min.js

# Plugin
plugins:
  - search:
      separator: '[\s\u200b\-]'  # 中文搜索, pip install jieba
      # 参考:https://squidfunk.github.io/mkdocs-material/blog/2022/05/05/chinese-search-support/?h=%E4%B8%AD%E6%96%87
  - statistics
  #- git-revision-date #每页底部显示文档最后更新日期，安装 pip install mkdocs-git-revision-date-plugin
  - git-revision-date-localized:  #每个页面底部添加本地化更新和创建日期，安装pip install mkdocs-git-revision-date-localized-plugin
      type: date #日期格式，有效值为date、datetime、iso_date、iso_datetime,timeago
      # fallback_to_build_date: true  #默认false，启用则回退到mkdocs build执行的时间
      enable_creation_date: true  #最后更新日期旁边显示与页面关联的文件的创建日期
  - glightbox: # 添加图像缩放功能
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extensions:
# Python Markdown
  - toc: #目录
      permalink: true # link for each title
      title: Table of Content 
    
  - admonition #警告或标注
  - pymdownx.details #细节折叠
  
  - attr_list #属性列表（按钮-颜色图标）
  - md_in_html # 允许添加HTML属性和CSS类到MD中
  - pymdownx.superfences: # 允许任意嵌套代码和内容块
      custom_fences: # 此配置启用对Mermaid.js图表的本机支持
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - abbr #缩写或名词
  - def_list #定义列表
  - footnotes #行内脚注
  - tables #表格
  - meta #元数据
  - toc:
      toc_depth: 4

  - pymdownx.arithmatex: #数学公式
      generic: true

  - pymdownx.betterem: #粗体斜体
      smart_enable: all

  - pymdownx.critic 
  - pymdownx.caret #插入角标符号(`^`)
  - pymdownx.keys #键盘键和组合  
  - pymdownx.mark #双等号(`==`)
  - pymdownx.tilde # 删除线
  - pymdownx.details
  - pymdownx.smartsymbols #智能符号

  - pymdownx.emoji: # 表情
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight #代码高亮，对代码块（SuperFences）和行内代码块（InlineHilite）的语法突出显示
  - pymdownx.inlinehilite #行内高亮
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.snippets: # 允许将其他文件内容插入文件，语法是 --8<-- "filename.ext" 等，参见 https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]

  - pymdownx.tabbed: #内容选项卡
      alternate_style: true 
  - pymdownx.tasklist: #任务列表
      custom_checkbox: true
