
# name: gh-deploy
# on:
#   push:
#     branches:
#       - master 
#       - main
# permissions:
#   contents: write
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Configure Git Credentials
#         run: |
#           git config user.name github-actions[bot]
#           git config user.email 41898282+github-actions[bot]@users.noreply.github.com
#       - uses: actions/setup-python@v4
#         with:
#           python-version: 3.x
#       - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
#       - uses: actions/cache@v3
#         with:
#           key: mkdocs-material-${{ env.cache_id }}
#           # publish_branch: gh-pages
#           # keep_files: true
#           path: .cache
#           restore-keys: |
#             mkdocs-material- 
#       - run: pip install jieba  
#       - run: pip install mkdocs-git-revision-date-localized-plugin
#       - run: pip install mkdocs-statistics-plugin
#       - run: pip install mkdocs-material 
#       - run: mkdocs gh-deploy --force


name: gh-deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install jieba
      #- run: pip install rich
      # - run: git clone https://github.com/smd1121/mkdocs-toolchain.git && cd mkdocs-toolchain/mkdocs-statistics-plugin && pip install -e .
      - run: pip install mkdocs-statistics-plugin
      - run: pip install neoteroi-mkdocs
      - run: mkdocs gh-deploy --force
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN  }}
          publish_dir: ./publish
          publish_branch: gh-pages
          keep_files: true
